%% Generated by the Erlang ASN.1 compiler. Version: 5.0.21
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module ReceiptModule.

-ifndef(_RECEIPTMODULE_HRL_).
-define(_RECEIPTMODULE_HRL_, true).

-record('ReceiptAttribute', {
  type,
  version,
  value
}).

-record('InAppAttribute', {
  type,
  version,
  value
}).

-endif. %% _RECEIPTMODULE_HRL_
